services:
  frontend:
    image: proneighborfrontend:latest
    container_name: proneighbor_frontend
    build:
      context: ./proneighbor
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    image: proneighborbackend:latest
    container_name: proneighbor_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: proneighbor_bd:latest
    container_name: proneighbor_bd_container
    build:
      context: ./db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=StrongP@ssword123
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/opt/mssql
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & /init-db.sh"

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
    driver: local
