
services:
  sqlserver:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssword123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - proneighbor_network

  backend:
    build:
      context: ./backend
    container_name: backend_container
    # REMOVE the environment section
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    networks:
      - proneighbor_network

  frontend:
    build:
      context: ./ProNeighbor
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - proneighbor_network

networks:
  proneighbor_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local