services:
  frontend:
    image: proneighborfrontend:latest
    container_name: proneighbor_frontend
    build:
      context: ./proneighbor
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    image: proneighborbackend:latest
    container_name: proneighbor_backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: proneighbor_bd_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=StrongP@ssword123
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "SA",
          "-P",
          "StrongP@ssword123",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      retries: 5
      start_period: 20s
    command: /opt/mssql/bin/sqlservr

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data:
    driver: local
