# docker-compose.yml
version: "3.8"

services:
  sqlserver:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssword123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - proneighbor_network

  backend:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      - DB_SERVER=sqlserver
      - DB_DATABASE=ProNeighbor2
      - DB_USER=sa
      - DB_PASSWORD=StrongP@ssword123
      - DB_PORT=1433
      - DB_ENCRYPT=true
      - DB_TRUST_SERVER_CERTIFICATE=true
      - JWT_SECRET=S3cReT!kEy@1234567890&*(A^VeRy$Tr0nG_SeCrEt_K3y
      - JWT_EXPIRATION=1h
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    networks:
      - proneighbor_network

  frontend:
    build:
      context: ./ProNeighbor
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "80:80"
    networks:
      - proneighbor_network

networks:
  proneighbor_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
