# Use Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables for SQL Server
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=StrongP@ssword123
ENV MSSQL_PID=Express

# Expose SQL Server port
EXPOSE 1433